FROM golang:1.26-bookworm AS builder
WORKDIR /src
COPY go.mod go.sum ./
COPY types/go.mod types/go.sum ./types/
COPY client/go.mod client/go.sum ./client/
RUN go mod download
COPY . .
RUN CGO_CFLAGS="-O1 -g" go build -tags "duckdb_arrow" -o /hugr-tools ./cmd/hugr-tools

FROM scratch
COPY --from=builder /hugr-tools /hugr-tools
