FROM golang:1.26-bookworm AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /hugr-tools ./cmd/hugr-tools

FROM scratch
COPY --from=builder /hugr-tools /hugr-tools
