package app

import (
	"fmt"

	"github.com/apache/arrow-go/v18/arrow"
)

// StructKind selects whether the struct is used as an output type
// (GraphQL OBJECT) or as an input type (GraphQL INPUT_OBJECT).
type StructKind int

const (
	// StructKindOutput produces a GraphQL Object type used as a function return.
	StructKindOutput StructKind = iota
	// StructKindInput produces a GraphQL InputObject type used as a function argument.
	StructKindInput
)

// StructType describes a custom GraphQL struct type generated by the SDK SDL
// builder. Use Struct or InputStruct to start a builder, add fields, then
// call AsType to convert it into a Type usable with Return / Arg.
//
// The wire representation is a JSON string. The hugr planner inlines complex
// argument values automatically; for return values the SDL emits @function
// (json_cast: true) so the planner casts the JSON output to the structured
// type before returning to the client.
type StructType struct {
	name        string
	kind        StructKind
	description string
	fields      []structField
}

// structField is the internal representation of a struct field.
type structField struct {
	name        string
	typ         Type
	nullable    bool
	isList      bool
	description string
	fieldSource string // optional @field_source(field: "...") for output structs
}

// Struct begins building an output struct (GraphQL Object type).
// The returned builder is mutable; chain Field/Desc/etc. and finish with AsType.
func Struct(name string) *StructType {
	return &StructType{name: name, kind: StructKindOutput}
}

// InputStruct begins building an input struct (GraphQL InputObject type).
func InputStruct(name string) *StructType {
	return &StructType{name: name, kind: StructKindInput}
}

// Desc sets the GraphQL doc description for the type.
func (s *StructType) Desc(description string) *StructType {
	s.description = description
	return s
}

// Field adds a non-null field of the given type.
// The type may be a scalar (e.g. app.String, app.Int64) or another struct
// via its AsType() method (the JSON wire format handles nesting).
func (s *StructType) Field(name string, typ Type) *StructType {
	s.fields = append(s.fields, structField{name: name, typ: typ})
	return s
}

// FieldDesc adds a non-null field with a description.
func (s *StructType) FieldDesc(name string, typ Type, description string) *StructType {
	s.fields = append(s.fields, structField{name: name, typ: typ, description: description})
	return s
}

// FieldNullable adds a nullable field of the given type.
func (s *StructType) FieldNullable(name string, typ Type) *StructType {
	s.fields = append(s.fields, structField{name: name, typ: typ, nullable: true})
	return s
}

// FieldList adds a non-null list field ([Type!]!). The element type may be
// any scalar or struct — JSON serialization handles nested arrays naturally.
func (s *StructType) FieldList(name string, typ Type) *StructType {
	s.fields = append(s.fields, structField{name: name, typ: typ, isList: true})
	return s
}

// FieldFromSource adds a non-null field whose underlying JSON key differs
// from the GraphQL name. The generated SDL emits a @field_source(field:
// "<originalName>") directive so the planner extracts the value from the
// underlying JSON correctly.
//
// Only valid on output structs. Panics if called on an input struct (caught
// at builder time as a programmer error).
func (s *StructType) FieldFromSource(name string, typ Type, originalName string) *StructType {
	if s.kind != StructKindOutput {
		panic(fmt.Sprintf("app.StructType.FieldFromSource: only valid on output structs, %q is an input struct", s.name))
	}
	s.fields = append(s.fields, structField{
		name:        name,
		typ:         typ,
		fieldSource: originalName,
	})
	return s
}

// AsType converts the struct definition into a Type usable with Return / Arg.
// The wire dt is arrow.BinaryTypes.String (JSON wire format); the GraphQL
// type name is the struct's name. The structDef back-pointer enables the SDL
// generator to emit the type definition alongside the function field.
func (s *StructType) AsType() Type {
	return Type{
		dt:        arrow.BinaryTypes.String,
		graphql:   s.name,
		structDef: s,
	}
}

// equalStructFields reports whether two struct types have identical fields,
// used by CatalogMux for type deduplication. Order is significant — fields
// at the same index must match in name, type, nullability, list-ness,
// description, and field source.
func equalStructFields(a, b *StructType) bool {
	if a == nil || b == nil {
		return a == b
	}
	if a.kind != b.kind || a.description != b.description {
		return false
	}
	if len(a.fields) != len(b.fields) {
		return false
	}
	for i := range a.fields {
		af, bf := a.fields[i], b.fields[i]
		if af.name != bf.name ||
			af.nullable != bf.nullable ||
			af.isList != bf.isList ||
			af.description != bf.description ||
			af.fieldSource != bf.fieldSource ||
			af.typ.graphql != bf.typ.graphql {
			return false
		}
	}
	return true
}
