package compiler

import (
	"strings"

	"github.com/hugr-lab/query-engine/pkg/catalog/compiler/base"
	"github.com/hugr-lab/query-engine/pkg/catalog/compiler/rules"
	"github.com/hugr-lab/query-engine/pkg/catalog/types"
	"github.com/vektah/gqlparser/v2/ast"
)

// emitFieldAddExtensions generates extensions for all derived types when a new
// scalar field is added to an existing type. Delegates to shared helpers in rules/.
func emitFieldAddExtensions(
	output *indexedOutput,
	typeName string,
	field *ast.FieldDefinition,
	opts base.Options,
	scalarLookup func(string) types.ScalarType,
) {
	rules.EmitScalarFieldDerivedTypes(output.AddExtension, typeName, field, opts, scalarLookup)
}

// emitFieldDropExtensions generates @drop(if_exists: true) extension fields
// for all derived types when a field is removed from a type.
func emitFieldDropExtensions(
	output *indexedOutput,
	typeName string,
	fieldName string,
	opts base.Options,
	typeExists func(string) bool,
) {
	rules.EmitScalarFieldDrop(output.AddExtension, typeName, fieldName, opts, typeExists)
}

// emitFieldReplaceExtensions combines drop + add for a field replacement.
func emitFieldReplaceExtensions(
	output *indexedOutput,
	typeName string,
	field *ast.FieldDefinition,
	opts base.Options,
	scalarLookup func(string) types.ScalarType,
	typeExists func(string) bool,
) {
	emitFieldDropExtensions(output, typeName, field.Name, opts, typeExists)
	emitFieldAddExtensions(output, typeName, field, opts, scalarLookup)
}

// emitVirtualFieldAddExtensions generates aggregation extensions when a virtual
// field (@join or @table_function_call_join or @function_call) is added.
func emitVirtualFieldAddExtensions(
	output *indexedOutput,
	typeName string,
	field *ast.FieldDefinition,
	opts base.Options,
	scalarLookup func(string) types.ScalarType,
	typeExists func(string) bool,
	_ func(string) *ast.Definition, // providerLookup — unused, kept for signature compat
) {
	rules.EmitVirtualFieldAggregations(output.AddExtension, typeName, field, opts, scalarLookup, typeExists)
}

// emitVirtualFieldDropExtensions drops aggregation fields generated by a virtual
// field (@join, @function_call, @table_function_call_join) when that field is dropped.
func emitVirtualFieldDropExtensions(
	output *indexedOutput,
	typeName string,
	fieldName string,
	existingField *ast.FieldDefinition,
	typeExists func(string) bool,
) {
	rules.EmitVirtualFieldAggDrop(output.AddExtension, typeName, fieldName, existingField, typeExists)
}

// emitReferenceDropExtensions drops all reference-generated fields when a
// field with @field_references is removed.
func emitReferenceDropExtensions(
	output *indexedOutput,
	typeDef *ast.Definition,
	fieldName string,
	typeExists func(string) bool,
) {
	rules.EmitReferenceFieldsDrop(output.AddExtension, typeDef, fieldName, typeExists)
}

// emitFunctionFieldDrop drops a function field and its aggregation fields.
func emitFunctionFieldDrop(
	output *indexedOutput,
	funcTypeName string,
	fieldName string,
	typeExists func(string) bool,
) {
	rules.EmitFunctionFieldDrop(output.AddExtension, funcTypeName, fieldName, typeExists)
}

// hasFieldReferences checks if an extension has any fields with @field_references.
func hasFieldReferences(ext *ast.Definition) bool {
	for _, f := range ext.Fields {
		if f.Directives.ForName("field_references") != nil {
			return true
		}
	}
	return false
}

// isIncrementalVirtualField checks if a field is virtual (function_call, join, table_function_call_join).
func isIncrementalVirtualField(f *ast.FieldDefinition) bool {
	return f.Directives.ForName("function_call") != nil ||
		f.Directives.ForName("table_function_call_join") != nil ||
		f.Directives.ForName("join") != nil
}

// emitModuleChangeExtensions moves a type's query/mutation fields from the old
// module type hierarchy to a new one when a type's @module directive changes.
func emitModuleChangeExtensions(
	output *indexedOutput,
	typeDef *ast.Definition,
	oldModule string,
	newModule string,
	opts base.Options,
	typeExists func(string) bool,
	providerLookup func(string) *ast.Definition,
) {
	pos := base.CompiledPos("incremental-module-change")

	// Compute full module paths (as_module prepends catalog name)
	oldModPath := oldModule
	newModPath := newModule
	if opts.AsModule {
		oldModPath = opts.Name + "." + oldModule
		newModPath = opts.Name + "." + newModule
	}

	oldQueryType := moduleLeafTypeName(oldModPath, "query")
	oldMutType := moduleLeafTypeName(oldModPath, "mutation")
	newQueryType := moduleLeafTypeName(newModPath, "query")
	newMutType := moduleLeafTypeName(newModPath, "mutation")

	// Extract field names from @query/@mutation directives on the type
	var queryFieldNames []string
	for _, d := range typeDef.Directives.ForNames(base.QueryDirectiveName) {
		if name := base.DirectiveArgString(d, base.ArgName); name != "" {
			queryFieldNames = append(queryFieldNames, name)
		}
	}
	var mutFieldNames []string
	for _, d := range typeDef.Directives.ForNames(base.MutationDirectiveName) {
		if name := base.DirectiveArgString(d, base.ArgName); name != "" {
			mutFieldNames = append(mutFieldNames, name)
		}
	}

	// Look up old module types in provider to copy field definitions
	oldQueryDef := providerLookup(oldQueryType)
	oldMutDef := providerLookup(oldMutType)

	modCatDir := incrementalModuleCatalogDirective(opts.Name, pos)

	// 1. Drop fields from old module types
	for _, fieldName := range queryFieldNames {
		rules.EmitDropFieldOnTypeIfExists(output.AddExtension, oldQueryType, fieldName, pos, typeExists)
	}
	for _, fieldName := range mutFieldNames {
		rules.EmitDropFieldOnTypeIfExists(output.AddExtension, oldMutType, fieldName, pos, typeExists)
	}

	// 2. Create new module types if they don't exist
	if !typeExists(newQueryType) {
		output.AddDefinition(&ast.Definition{
			Kind:     ast.Object,
			Name:     newQueryType,
			Position: pos,
			Directives: ast.DirectiveList{
				incrementalModuleRootDirective(newModPath, "QUERY", pos),
				modCatDir,
			},
			Fields: ast.FieldList{
				{Name: "_stub", Type: ast.NamedType("Boolean", pos), Position: pos},
			},
		})
	}
	if len(mutFieldNames) > 0 && !typeExists(newMutType) {
		output.AddDefinition(&ast.Definition{
			Kind:     ast.Object,
			Name:     newMutType,
			Position: pos,
			Directives: ast.DirectiveList{
				incrementalModuleRootDirective(newModPath, "MUTATION", pos),
				modCatDir,
			},
			Fields: ast.FieldList{
				{Name: "_stub", Type: ast.NamedType("Boolean", pos), Position: pos},
			},
		})
	}

	// 3. Copy fields from old module types to new ones
	if oldQueryDef != nil {
		var fields ast.FieldList
		for _, name := range queryFieldNames {
			if f := oldQueryDef.Fields.ForName(name); f != nil {
				fields = append(fields, f)
			}
		}
		if len(fields) > 0 {
			output.AddExtension(&ast.Definition{
				Kind: ast.Object, Name: newQueryType, Position: pos,
				Fields: fields,
			})
		}
	}
	if oldMutDef != nil {
		var fields ast.FieldList
		for _, name := range mutFieldNames {
			if f := oldMutDef.Fields.ForName(name); f != nil {
				fields = append(fields, f)
			}
		}
		if len(fields) > 0 {
			output.AddExtension(&ast.Definition{
				Kind: ast.Object, Name: newMutType, Position: pos,
				Fields: fields,
			})
		}
	}

	// 4. Add new module entry on Query/Mutation if the module root doesn't exist yet
	topMod := strings.Split(newModPath, ".")[0]
	topModQueryType := newQueryType
	topModMutType := newMutType
	// For dotted paths, the top-level type uses only the first segment
	if strings.Contains(newModPath, ".") {
		topModQueryType = moduleLeafTypeName(topMod, "query")
		topModMutType = moduleLeafTypeName(topMod, "mutation")
	}

	if queryDef := providerLookup("Query"); queryDef != nil {
		if queryDef.Fields.ForName(topMod) == nil {
			output.AddExtension(&ast.Definition{
				Kind: ast.Object, Name: "Query", Position: pos,
				Fields: ast.FieldList{
					{Name: topMod, Type: ast.NamedType(topModQueryType, pos), Position: pos,
						Directives: ast.DirectiveList{modCatDir}},
				},
			})
		}
	}
	if len(mutFieldNames) > 0 {
		if mutDef := providerLookup("Mutation"); mutDef != nil {
			if mutDef.Fields.ForName(topMod) == nil {
				output.AddExtension(&ast.Definition{
					Kind: ast.Object, Name: "Mutation", Position: pos,
					Fields: ast.FieldList{
						{Name: topMod, Type: ast.NamedType(topModMutType, pos), Position: pos,
							Directives: ast.DirectiveList{modCatDir}},
					},
				})
			}
		}
	}
}

// detectModuleChange checks if extension directives represent a module change.
// Returns (oldModule, newModule) — either may be empty if not detectable.
func detectModuleChange(directives ast.DirectiveList) (oldModule, newModule string) {
	for _, d := range directives.ForNames(base.DropDirectiveDirectiveName) {
		if base.DirectiveArgString(d, "name") == base.ModuleDirectiveName {
			// Extract old module name from match argument
			if matchArg := d.Arguments.ForName("match"); matchArg != nil && matchArg.Value != nil {
				for _, child := range matchArg.Value.Children {
					if child.Name == "name" {
						oldModule = child.Value.Raw
					}
				}
			}
		}
	}
	if md := directives.ForName(base.ModuleDirectiveName); md != nil {
		newModule = base.DirectiveArgString(md, base.ArgName)
	}
	return
}

// moduleLeafTypeName computes the module type name for a given module path and suffix.
func moduleLeafTypeName(modPath, suffix string) string {
	return "_module_" + strings.ReplaceAll(modPath, ".", "_") + "_" + suffix
}

// incrementalModuleRootDirective creates a @module_root(name, type) directive.
func incrementalModuleRootDirective(modPath, rootType string, pos *ast.Position) *ast.Directive {
	return &ast.Directive{
		Name: base.ModuleRootDirectiveName,
		Arguments: ast.ArgumentList{
			{Name: "name", Value: &ast.Value{Raw: modPath, Kind: ast.StringValue, Position: pos}, Position: pos},
			{Name: "type", Value: &ast.Value{Raw: rootType, Kind: ast.EnumValue, Position: pos}, Position: pos},
		},
		Position: pos,
	}
}

// incrementalModuleCatalogDirective creates a @module_catalog(name) directive.
func incrementalModuleCatalogDirective(catalogName string, pos *ast.Position) *ast.Directive {
	return &ast.Directive{
		Name: base.ModuleCatalogDirectiveName,
		Arguments: ast.ArgumentList{
			{Name: "name", Value: &ast.Value{Raw: catalogName, Kind: ast.StringValue, Position: pos}, Position: pos},
		},
		Position: pos,
	}
}
