package planner

import (
	"context"
	"fmt"
	"strings"

	"github.com/apache/arrow-go/v18/arrow"
	arrowingest "github.com/hugr-lab/query-engine/pkg/arrow-ingest"
	"github.com/hugr-lab/query-engine/pkg/auth"
	"github.com/hugr-lab/query-engine/pkg/catalog"
	"github.com/hugr-lab/query-engine/pkg/catalog/compiler/base"
	"github.com/hugr-lab/query-engine/pkg/catalog/sdl"
	"github.com/hugr-lab/query-engine/pkg/engines"
	"github.com/hugr-lab/query-engine/pkg/perm"
	"github.com/vektah/gqlparser/v2/ast"
)

type ingestColumn struct {
	ArrowField arrow.Field
	Field      *sdl.Field
	FieldDef   *ast.FieldDefinition
	InputDef   *ast.FieldDefinition
}

func ingestRootNode(ctx context.Context, provider catalog.Provider, planner Catalog, dataObject string, source arrowingest.Source) (*QueryPlanNode, error) {
	if dataObject == "" {
		return nil, fmt.Errorf("missing data object")
	}
	if source.Reader == nil {
		return nil, fmt.Errorf("missing arrow reader")
	}
	if source.View() == "" {
		return nil, fmt.Errorf("missing arrow view name")
	}

	info, mutationField, err := resolveIngestTarget(ctx, provider, dataObject)
	if err != nil {
		return nil, err
	}
	engine, err := planner.Engine(info.Catalog)
	if err != nil {
		return nil, err
	}
	caps := engine.Capabilities()
	if caps == nil {
		return nil, fmt.Errorf("engine %q does not support IPC ingest", engine.Type())
	}
	if !caps.Ingest.Valid() {
		return nil, fmt.Errorf("engine %q has invalid ingest capabilities: merge requires insert", engine.Type())
	}
	if !caps.Ingest.Available() {
		return nil, fmt.Errorf("engine %q does not support IPC ingest", engine.Type())
	}
	ingestEngine, ok := engine.(engines.EngineArrowIngestCaster)
	if !ok {
		return nil, fmt.Errorf("engine %q declares IPC ingest support but does not implement Arrow ingest casting", engine.Type())
	}
	mutation := sdl.MutationInfo(ctx, provider, mutationField)
	if mutation == nil || mutation.Type != sdl.MutationTypeInsert {
		return nil, fmt.Errorf("data object %q has no insert mutation defined", dataObject)
	}

	permissionData, err := resolveIngestPermissionData(ctx, provider, info, mutationField)
	if err != nil {
		return nil, err
	}
	columns, err := resolveIngestColumns(ctx, provider, info, mutation, source.Reader.Schema(), permissionData)
	if err != nil {
		return nil, err
	}
	if len(columns) == 0 {
		return nil, fmt.Errorf("no insertable columns matched between arrow stream and data object")
	}
	if err := checkIngestPermissions(ctx, provider, info, columns, permissionData); err != nil {
		return nil, err
	}
	return ingestNode(ctx, info, mutation, ingestEngine, columns, permissionData, source.View()), nil
}

func resolveIngestTarget(ctx context.Context, provider catalog.Provider, dataObject string) (*sdl.Object, *ast.FieldDefinition, error) {
	var def *ast.Definition
	if strings.Contains(dataObject, ".") {
		queryDef := provider.ForName(ctx, base.QueryBaseName)
		if queryDef == nil {
			return nil, nil, fmt.Errorf("query base type not found in schema")
		}
		cur := queryDef
		for _, part := range strings.Split(dataObject, ".") {
			f := cur.Fields.ForName(part)
			if f == nil {
				return nil, nil, fmt.Errorf("data object %q: segment %q not found", dataObject, part)
			}
			cur = provider.ForName(ctx, f.Type.Name())
			if cur == nil {
				return nil, nil, fmt.Errorf("data object %q: type %q not found", dataObject, f.Type.Name())
			}
		}
		def = cur
	} else {
		def = provider.ForName(ctx, dataObject)
	}
	if def == nil {
		return nil, nil, fmt.Errorf("data object %q not found in schema", dataObject)
	}
	if !sdl.IsDataObject(def) {
		return nil, nil, fmt.Errorf("%q is not a data object", dataObject)
	}
	info := sdl.DataObjectInfo(def)
	if info == nil {
		return nil, nil, fmt.Errorf("data object %q: no info", dataObject)
	}
	if info.Type != sdl.TableDataObject {
		return nil, nil, fmt.Errorf("data object %q is not a table (got %q): only tables are ingestable", dataObject, info.Type)
	}
	if info.Catalog == "" {
		return nil, nil, fmt.Errorf("data object %q has no catalog", dataObject)
	}
	_, mutationField := sdl.ObjectMutationDefinition(ctx, provider, def, sdl.MutationTypeInsert)
	if mutationField == nil {
		return nil, nil, fmt.Errorf("data object %q has no insert mutation defined", dataObject)
	}
	return info, mutationField, nil
}

// resolveIngestColumns matches Arrow IPC stream columns to the GraphQL insert
// contract for the target table data object.
//
//   - provider resolves GraphQL definitions generated by the catalog compiler.
//   - info describes the GraphQL data object and its DB table/field mapping.
//   - mutation describes the GraphQL insert mutation and insertable fields.
//   - schema is the Arrow IPC schema supplied by the request body.
//   - permissionData contains fields injected by permissions; required fields
//     can be satisfied by either Arrow columns or these injected values.
//
// The returned ingestColumn values keep all three names/spaces together:
// Arrow field, GraphQL object/input field, and DB table column mapping.
func resolveIngestColumns(ctx context.Context, provider catalog.Provider, info *sdl.Object, mutation *sdl.Mutation, schema *arrow.Schema, permissionData map[string]any) ([]ingestColumn, error) {
	if schema == nil {
		return nil, fmt.Errorf("arrow stream has no schema")
	}
	// GraphQL input type accepted by the insert mutation, for example
	// events_mut_input_data. Arrow columns must be valid fields of this input.
	inputName := info.InputInsertDataName()
	if inputName == "" {
		return nil, fmt.Errorf("data object %q has no insert input type", info.Name)
	}
	// GraphQL definition of the insert input object. This is not the DB table;
	// it is the public mutation contract used for permission/input validation.
	input := provider.ForName(ctx, inputName)
	if input == nil {
		return nil, fmt.Errorf("insert input type %q not found", inputName)
	}

	// seen detects duplicate Arrow column names before they collapse into the
	// byName lookup map below.
	seen := map[string]struct{}{}
	// byName stores the resolved ingest metadata keyed by GraphQL/Arrow field
	// name. Field source directives may later map this name to another DB column.
	byName := make(map[string]ingestColumn, schema.NumFields())
	for _, af := range schema.Fields() {
		// af is the physical Arrow IPC column. Its name is matched against the
		// GraphQL insert input and data object field names.
		if _, dup := seen[af.Name]; dup {
			return nil, fmt.Errorf("duplicate arrow column %q", af.Name)
		}
		seen[af.Name] = struct{}{}

		// inputField is the GraphQL mutation input field. If it is absent, the
		// client is trying to ingest a column that the insert API does not expose.
		inputField := input.Fields.ForName(af.Name)
		if inputField == nil {
			return nil, fmt.Errorf("column %q is not defined in insert input %q", af.Name, inputName)
		}
		// objectField is the GraphQL field on the table data object. It carries
		// type information and directives such as @geometry_info / @field_source.
		objectField := info.Definition().Fields.ForName(af.Name)
		if objectField == nil {
			return nil, fmt.Errorf("column %q is not defined in data object %q", af.Name, info.Definition().Name)
		}
		// fieldInfo is the compiled catalog view of objectField. It knows whether
		// the GraphQL field is a real DB field, a reference, or a computed field,
		// and how it maps to the table column.
		fieldInfo := info.FieldForName(af.Name)
		if fieldInfo == nil {
			return nil, fmt.Errorf("column %q is not defined in data object %q", af.Name, info.Definition().Name)
		}
		if fieldInfo.IsReferencesSubquery() {
			return nil, fmt.Errorf("column %q is a reference and cannot be ingested directly", af.Name)
		}
		if fieldInfo.IsNotDBField() {
			return nil, fmt.Errorf("column %q is a computed/virtual field and cannot be ingested", af.Name)
		}
		if fieldInfo.FieldSourceName("", false) == "-" {
			return nil, fmt.Errorf("column %q has no database mapping", af.Name)
		}
		byName[af.Name] = ingestColumn{
			ArrowField: af,
			Field:      fieldInfo,
			FieldDef:   objectField,
			InputDef:   inputField,
		}
	}

	// Check required GraphQL insert fields that were not supplied by Arrow.
	// Required fields are allowed to be omitted only when the DB/catalog can
	// provide them through a sequence, default insert expression, or @default.
	for _, fieldInfo := range mutation.Fields() {
		if _, ok := byName[fieldInfo.Name]; ok {
			continue
		}
		if _, ok := permissionData[fieldInfo.Name]; ok {
			continue
		}
		if !fieldInfo.IsRequired() {
			continue
		}
		if fieldInfo.SequenceName() != "" || mutation.FieldHasDefaultInsertExpr(fieldInfo.Name) {
			continue
		}
		if fd := info.Definition().Fields.ForName(fieldInfo.Name); fd != nil &&
			fd.Directives.ForName(base.FieldDefaultDirectiveName) != nil {
			continue
		}
		return nil, fmt.Errorf("field %q is required for ingest into %q", fieldInfo.Name, info.Name)
	}

	// Preserve Arrow stream column order for the SELECT list. The map above is
	// only for validation and required-field checks.
	columns := make([]ingestColumn, 0, len(byName))
	for _, af := range schema.Fields() {
		columns = append(columns, byName[af.Name])
	}
	return columns, nil
}

func resolveIngestPermissionData(ctx context.Context, provider catalog.Provider, info *sdl.Object, mutationField *ast.FieldDefinition) (map[string]any, error) {
	if auth.IsFullAccess(ctx) {
		return nil, nil
	}
	rp := perm.PermissionsFromCtx(ctx)
	if rp == nil {
		return nil, nil
	}
	if rp.Disabled {
		return nil, auth.ErrForbidden
	}

	parent := sdl.ModuleTypeName(sdl.ObjectModule(info.Definition()), sdl.ModuleMutation)
	if _, ok := rp.Enabled(parent, mutationField.Name); !ok {
		return nil, auth.ErrForbidden
	}

	arg := rp.DataArgument(ctx, parent, mutationField.Name)
	if arg == nil {
		return nil, nil
	}
	values, err := sdl.ParseDataAsInputObject(ctx, provider, &ast.Type{
		NamedType: info.InputInsertDataName(),
		Position:  base.CompiledPos("ingest permission data"),
	}, arg, false)
	if err != nil {
		return nil, err
	}
	if values == nil {
		return nil, nil
	}
	return values.(map[string]any), nil
}

func checkIngestPermissions(ctx context.Context, provider catalog.Provider, info *sdl.Object, columns []ingestColumn, permissionData map[string]any) error {
	if auth.IsFullAccess(ctx) {
		return nil
	}
	rp := perm.PermissionsFromCtx(ctx)
	if rp == nil {
		return nil
	}
	if rp.Disabled {
		return auth.ErrForbidden
	}

	data := make(map[string]any, len(columns)+len(permissionData))
	for _, c := range columns {
		data[c.InputDef.Name] = nil
	}
	for k, v := range permissionData {
		data[k] = v
	}
	if err := rp.CheckMutationInput(ctx, provider, info.InputInsertDataName(), data); err != nil {
		return err
	}
	return nil
}

// ingestNode builds the INSERT ... SELECT statement that copies rows from the
// request-scoped DuckDB Arrow view into the target DB table.
//
//   - info is the GraphQL data object plus its DB table/column mapping.
//   - mutation is the GraphQL insert mutation used for insert defaults.
//   - engine converts Arrow-view expressions into values accepted by the
//     target engine/table.
//   - columns are Arrow columns already resolved to GraphQL fields and DB
//     columns by resolveIngestColumns.
//   - permissionData contains extra GraphQL input values injected by the
//     permission layer; they do not come from the Arrow stream.
//   - arrowViewName is the globally unique DuckDB view registered from the
//     Arrow reader for this ingest execution.
func ingestNode(ctx context.Context, info *sdl.Object, mutation *sdl.Mutation, engine engines.EngineArrowIngestCaster, columns []ingestColumn, permissionData map[string]any, arrowViewName string) *QueryPlanNode {
	return &QueryPlanNode{
		Name: "ingest_" + info.Name,
		CollectFunc: func(node *QueryPlanNode, children Results, params []any) (string, []any, error) {
			// fieldValues is keyed by GraphQL field name. Each value is a SQL
			// expression evaluated in the SELECT part of INSERT ... SELECT.
			// The expression may reference an Arrow column from the ingest
			// DuckDB view, or it may be a constant/default/permission value.
			fieldValues := make(map[string]string, len(columns))
			for _, c := range columns {
				// c.ArrowField.Name is the physical Arrow view column name.
				// It is not necessarily the final DB column name; @field_source
				// is applied later when targetFields is built.
				value := engines.Ident(c.ArrowField.Name)
				// Synthetic GraphQL field used only to pass type/directive
				// metadata to the engine-specific Arrow ingest caster.
				field := ingestASTField(info, c.Field, c.FieldDef)
				// Build the Arrow ingest SELECT expression for the target
				// GraphQL/DB field.
				// Examples: JSON to_json(...) or DuckDB staging geometry
				// expressions used for both DuckDB and attached Postgres targets.
				value, err := engine.ArrowIngestSelectExpr(field, c.ArrowField, value)
				if err != nil {
					return "", nil, err
				}
				fieldValues[c.Field.Name] = value
			}
			for name, value := range permissionData {
				// Permission data is addressed by GraphQL input/object field
				// name, then converted to a staging SQL literal/expression.
				fieldInfo := info.FieldForName(name)
				if fieldInfo == nil {
					return "", nil, fmt.Errorf("permission data field %q is not defined in data object %q", name, info.Name)
				}
				if fieldInfo.IsReferencesSubquery() || fieldInfo.IsNotDBField() {
					return "", nil, fmt.Errorf("permission data field %q cannot be ingested directly", name)
				}
				fieldDef := info.Definition().Fields.ForName(name)
				if fieldDef == nil {
					return "", nil, fmt.Errorf("permission data field %q definition not found in data object %q", name, info.Name)
				}
				// Unlike Arrow columns, this value has no Arrow type. The target
				// engine still decides how to shape the literal for ingest.
				sqlValue, err := engine.ArrowIngestLiteralExpr(ingestASTField(info, fieldInfo, fieldDef), value)
				if err != nil {
					return "", nil, err
				}
				fieldValues[name] = sqlValue
			}
			// Arrow ingest SELECT expressions are evaluated by DuckDB because
			// the Arrow view is registered in DuckDB.
			// Default/auth helper expressions must therefore use the same canonical
			// DuckDB staging types before optional target casting is applied below.
			if err := mutation.AppendInsertSQLExpression(fieldValues, perm.AuthVars(ctx), engines.NewArrowIngestStagingBuilder()); err != nil {
				return "", nil, err
			}
			var targetFields, selectExprs []string
			for _, c := range columns {
				// targetFields are DB table columns. FieldSourceName applies the
				// catalog mapping from GraphQL field name to physical DB column.
				targetFields = append(targetFields, c.Field.FieldSourceName("", true))
				// selectExprs are evaluated from the DuckDB Arrow view and must
				// stay in the same order as targetFields.
				expr, err := castIngestValueToTarget(engine, ingestASTField(info, c.Field, c.FieldDef), fieldValues[c.Field.Name])
				if err != nil {
					return "", nil, err
				}
				selectExprs = append(selectExprs, expr)
				delete(fieldValues, c.Field.Name)
			}
			for _, fieldInfo := range mutation.Fields() {
				// Remaining fieldValues are values not backed by Arrow columns:
				// permission data and default insert expressions.
				expr, ok := fieldValues[fieldInfo.Name]
				if !ok {
					continue
				}
				if fieldInfo.FieldSourceName("", false) == "-" {
					continue
				}
				fieldDef := info.Definition().Fields.ForName(fieldInfo.Name)
				if fieldDef == nil {
					return "", nil, fmt.Errorf("ingest field %q definition not found in data object %q", fieldInfo.Name, info.Name)
				}
				expr, err := castIngestValueToTarget(engine, ingestASTField(info, fieldInfo, fieldDef), expr)
				if err != nil {
					return "", nil, err
				}
				targetFields = append(targetFields, fieldInfo.FieldSourceName("", true))
				selectExprs = append(selectExprs, expr)
				delete(fieldValues, fieldInfo.Name)
			}
			if len(targetFields) == 0 {
				return "", nil, fmt.Errorf("no values provided for ingest")
			}

			target := info.SQL(ctx, engines.Ident(info.Catalog))
			// The FROM relation is this ingest request's globally unique Arrow view.
			return fmt.Sprintf("INSERT INTO %s (%s) SELECT %s FROM %s",
				target,
				strings.Join(targetFields, ", "),
				strings.Join(selectExprs, ", "),
				engines.Ident(arrowViewName),
			), params, nil
		},
	}
}

func castIngestValueToTarget(engine engines.EngineArrowIngestCaster, field *ast.Field, stagingExpr string) (string, error) {
	targetCaster, ok := engine.(engines.EngineIngestTargetCaster)
	if !ok {
		return stagingExpr, nil
	}
	return targetCaster.CastIngestValueToTarget(field, stagingExpr)
}

func ingestASTField(info *sdl.Object, fieldInfo *sdl.Field, fieldDef *ast.FieldDefinition) *ast.Field {
	return &ast.Field{
		Name:             fieldInfo.Name,
		Alias:            fieldInfo.Name,
		Definition:       fieldDef,
		ObjectDefinition: info.Definition(),
	}
}
